# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2021, Konrad Weihmann
name: 'bitbake testimage'
description: 'builds a single image and then run testimage class on it'
inputs:
  target: 
    description: 'image to check'
    required: true
  tapgen: 
    description: 'run tapgen'
    required: false
    default: "1"
  ignore-exit-codes:
    description: 'space seperated list of exit codes to ignore as failures'
    required: false
    default: ""
  clean-skip:
    description: 'Temporary directories to keep'
    required: false
    default: "hosttools sysroots-uninative"
runs:
  using: "composite"
  steps:
    - name: build
      run: |
        BUILD_ACCEPTABLE_EC="${{ inputs.ignore-exit-codes }}" \
        /github/actions/scripts/testimage \
        --target=${{ inputs.target }} \
        --clean_skip="${{ inputs.clean-skip }}" \
        --tapgen=${{ inputs.tapgen }}
      shell: bash
