# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2021, Konrad Weihmann
name: 'Run flake8'
description: 'run flake8'
inputs:
  sources:
    description: 'dir with the sources'
    required: true
  config-file: 
    description: 'custom configuration file'
    required: false
    default: ''
  username:
    description: 'username to use for comments'
    required: true
  token:
    description: 'token to use for comments'
    required: true
  pull-request-repo-user:
    description: 'github username of repo'
    required: true
  pull-request-repo:
    description: 'github repo'
    required: true
runs:
  using: "composite"
  steps:
    - name: install
      run: |
        sudo pip3 install --upgrade pip
        sudo pip3 install setuptools
        sudo pip3 install requests
        sudo pip3 install flake8
        sudo pip3 install github3.py
      shell: bash
    - name: run
      run: |
        EXPORT_BOT_WEBSECRET=${{ inputs.token }} \
        /github/actions/scripts/oelint \
        --configfile="${{ inputs.config-file }}" \
        "${{ inputs.sources }}" \
        "${{ inputs.username }}" \
        "${{ inputs.pull-request-repo-user }}" \
        "${{ inputs.pull-request-repo }}"
      shell: bash
