# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2020, Konrad Weihmann
name: 'export results'
description: '...export the web results'
inputs:
  branch: 
    description: 'SCA branch to use'
    required: true
  parameter-file:
    description: 'Parameter file'
    required: true
  deploy-token:
    description: 'Github token for webdeploy'
    required: true
  repo:
    description: 'Repository name'
    required: false
    default: "priv-kweihmann.github.io"
  ignore-exit-codes:
    description: 'space seperated list of exit codes to ignore as failures'
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: export results
      run: |
        BUILD_ACCEPTABLE_EC="${{ inputs.ignore-exit-codes }}" \
        EXPORT_BOT_WEBSECRET=${{ inputs.deploy-token }} /github/actions/scripts/exportfindings \
        --modfilename=${{ inputs.parameter-file }} \
        --branch=${{ inputs.branch }} \
        --repo=${{ inputs.repo }}
      shell: bash