# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2020, Konrad Weihmann
name: 'build modules'
description: 'builds meta-sca modules'
inputs:
  parameter-file: 
    description: 'Parameter file'
    required: true
  repo:
    description: 'Repo to use'
    required: false
    default: "meta-sca"
  ignore-exit-codes:
    description: 'space seperated list of exit codes to ignore as failures'
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: build
      run: |
        BUILD_ACCEPTABLE_EC="${{ inputs.ignore-exit-codes }}" \
        /github/actions/scripts/buildntest \
        --modfile=${WORKSPACE}/sources/${{ inputs.repo }}/test/lang_${{ inputs.parameter-file }}.txt \
        --repo=${{ inputs.repo }}
      shell: bash