#!/bin/bash
# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2020, Konrad Weihmann
set -e

[ -z "${WORKSPACE}" ] && WORKSPACE=$PWD

TARGET=""
CLEAN_SKIP=""

THISDIR="$(dirname $0)"

usage() {
    echo "$(basename $0) - build bitbake target"
    echo "--target - target to build"
    echo "--clean_skip - cleanup skips"
}

[ "$#" -eq "0" ] && usage && exit 0

for i in "$@"
do
case $i in
    --target=*)
        TARGET="${i#*=}"
        shift
        ;;
    --clean_skip=*)
        CLEAN_SKIP="${CLEAN_SKIP} ${i#*=}"
        shift
        ;;
    *)
        usage && exit 0
        ;;
esac
done

[ -z "${TARGET}" ] && usage && exit 1

source ${THISDIR}/utils

setup_bitbake
${THISDIR}/time_budget bitbake ${TARGET}
# shellcheck disable=SC2086
clean ${CLEAN_SKIP} || true
