#!/bin/bash
# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2020, Konrad Weihmann
set -e

[ -z "${WORKSPACE}" ] && WORKSPACE=$PWD

MODFILE=""
CLEAN_SKIP=""
BUILDNTEST_PRESERVECACHE="1"
BUILDNTEST_NOTEST="1"
REPO="meta-sca"

THISDIR="$(dirname $0)"

usage() {
    echo "$(basename $0) - build'n'test modules"
    echo "--modfile - modfile to test"
    echo "--clean_skip - cleanup skips"
    echo "--preservecache - Preserve existing caches (set 0 to disable)"
    echo "--notest - Don't test results (set 0 to disable)"
    echo "--repo - repo name to use (default: meta-sca)"
}

[ "$#" -eq "0" ] && usage && exit 0

for i in "$@"
do
case $i in
    --modfile=*)
        MODFILE="${i#*=}"
        shift
        ;;
    --clean_skip=*)
        CLEAN_SKIP="${CLEAN_SKIP} ${i#*=}"
        shift
        ;;
    --preservecache=*)
        BUILDNTEST_PRESERVECACHE="${i#*=}"
        shift
        ;;
    --notest=*)
        BUILDNTEST_NOTEST="${i#*=}"
        shift
        ;;
    --repo=*)
        REPO="${i#*=}"
        shift
        ;;
    *)
        usage && exit 0
        ;;
esac
done

[ -z "${MODFILE}" ] && usage && exit 1

source ${THISDIR}/utils

export BUILDNTEST_PRESERVECACHE
export BUILDNTEST_NOTEST

setup_bitbake
${THISDIR}/time_budget ${WORKSPACE}/sources/${REPO}/test/buildntest ${MODFILE}
# shellcheck disable=SC2086
clean ${CLEAN_SKIP} || true
