#!/bin/bash
# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2020, Konrad Weihmann
set -e

[ -z "${WORKSPACE}" ] && WORKSPACE=$PWD

TARGET=""
CLEAN="1"

THISDIR="$(dirname $0)"

usage() {
    echo "$(basename $0) - build bitbake target"
    echo "--target - target to build"
    echo "--clean - cleanup afterwards (set 0 to disable)"
}

[ "$#" -eq "0" ] && usage && exit 0

for i in "$@"
do
case $i in
    --target=*)
        TARGET="${i#*=}"
        shift
        ;;
    --clean=*)
        CLEAN="${i#*=}"
        shift
        ;;
    *)
        usage && exit 0
        ;;
esac
done

[ -z "${TARGET}" ] && usage && exit 1

source ${THISDIR}/utils

setup_bitbake
${THISDIR}/time_budget bitbake ${TARGET}
[ "${CLEAN}" -ne "0" ] && clean_all || true
# print 50 biggest disk consumers
du -ah "${WORKSPACE}" | sort -rh | head -n 50
