#!/bin/bash
# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2020, Konrad Weihmann
set -e

[ -z "${WORKSPACE}" ] && WORKSPACE=$PWD

MODFILE=""
CLEAN_SKIP=""
REPO="meta-sca"

THISDIR="$(dirname $0)"

usage() {
    echo "$(basename $0) - check results of modules"
    echo "--modfile - modfile to test"
    echo "--clean_skip - cleanup skips"
    echo "--repo - repo name to use (default: meta-sca)"
}

[ "$#" -eq "0" ] && usage && exit 0

for i in "$@"
do
case $i in
    --modfile=*)
        MODFILE="${i#*=}"
        shift
        ;;
    --clean_skip=*)
        CLEAN_SKIP="${i#*=}"
        shift
        ;;
    --repo=*)
        REPO="${i#*=}"
        shift
        ;;
    *)
        usage && exit 0
        ;;
esac
done

[ -z "${MODFILE}" ] && usage && exit 1

if [ ! -f "${MODFILE}" ]; then
    MODFILE=$(find ${WORKSPACE}/sources/${REPO}/test -type f -name "*${MODFILE}*" | head -n1 )
fi

[ -z "${MODFILE}" ] && echo "--modfile not found" && exit 2

source ${THISDIR}/utils

setup_bitbake
sca_export_dir="$(get_var_from_bitbake SCA_EXPORT_DIR busybox)"
[ -z "${sca_export_dir}" ] && echo "Can't determine the SCA_EXPORT_DIR" && exit 1
${THISDIR}/time_budget ${WORKSPACE}/sources/${REPO}/test/check_results "${sca_export_dir}" ${MODFILE}
# shellcheck disable=SC2086
clean "${CLEAN_SKIP}" || true
