#!/bin/bash
# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2020, Konrad Weihmann
set -e
exec 2>&1

[ -z "${WORKSPACE}" ] && WORKSPACE=$PWD

THISDIR="$(dirname $0)"

BRANCH=""
MODFILENAME=""
WEBREPO="priv-kweihmann.github.io"
REPOUSER="priv-kweihmann"

usage() {
    echo "$(basename $0) - export findings"
    echo "--modfilename - Name of modfile to use"
    echo "--branch - branch to export"
    echo "--repo - name of the repository"
}

[ "$#" -eq "0" ] && usage && exit 0

for i in "$@"
do
case $i in
    --modfilename=*)
        MODFILENAME="${i#*=}"
        shift
        ;;
    --branch=*)
        BRANCH="${i#*=}"
        shift
        ;;
    --repo=*)
        WEBREPO="${i#*=}"
        shift
        ;;
    --repouser=*)
        REPOUSER="${i#*=}"
        shift
        ;;
    *)
        usage && exit 0
        ;;
esac
done

[ -z "${BRANCH}" ] && usage && exit 1
[ -z "${MODFILENAME}" ] && usage && exit 1

source ${THISDIR}/utils

_sca_export_dir="$(get_var_from_bitbake SCA_EXPORT_DIR)"
_sca_export_find_dir="$(get_var_from_bitbake SCA_EXPORT_FINDING_DIR)"

setup_bitbake

# Create changeset

mkdir -p ${WORKSPACE}/sources/${WEBREPO}/data/${BRANCH}/
${THISDIR}/time_budget ${WORKSPACE}/sources/${WEBREPO}/tools/report ${_sca_export_dir} ${_sca_export_find_dir} \
    ${WORKSPACE}/sources/${WEBREPO}/data/${BRANCH}/${MODFILENAME}.json
if [ ! -e "${WORKSPACE}/sources/${WEBREPO}/data/${SCABRANCH}/result.json" ]; then
    echo '{}' > ${WORKSPACE}/sources/${WEBREPO}/data/${SCABRANCH}/result.json
fi
${THISDIR}/time_budget ${WORKSPACE}/sources/${WEBREPO}/tools/jsonmerge \
    ${WORKSPACE}/sources/${WEBREPO}/data/${BRANCH}/result.json \
    ${WORKSPACE}/sources/${WEBREPO}/data/${BRANCH}/*.json

# Export via git
cd ${WORKSPACE}/sources/${WEBREPO}
git add .
git config --local user.email "web@deploy.bot"
git config --local user.name "Webdeploy bot"
git remote rm origin
git remote add origin https://${REPOUSER}:${EXPORT_BOT_WEBSECRET}@github.com/${REPOUSER}/${WEBREPO}.git
git diff --quiet && git diff --staged --quiet || (git commit --amend -m "Update findings"; git push origin master --force) || true
cd -