#!/bin/bash
# SPDX-License-Identifier: BSD-2-Clause
# Copyright (c) 2021, Konrad Weihmann
set -e

[ -z "${WORKSPACE}" ] && WORKSPACE=$PWD

TARGET=""
CLEAN_SKIP=""
TAPGEN="1"

THISDIR="$(dirname $0)"

usage() {
    echo "$(basename $0) - run a testimage"
    echo "--target - target to build"
    echo "--tapgen - run tapgen"
    echo "--clean_skip - cleanup skips"
}

[ "$#" -eq "0" ] && usage && exit 0

for i in "$@"
do
case $i in
    --target=*)
        TARGET="${i#*=}"
        shift
        ;;
    --clean_skip=*)
        CLEAN_SKIP="${CLEAN_SKIP} ${i#*=}"
        shift
        ;;
    --tapgen=*)
        TAPGEN="${i#*=}"
        shift
        ;;
    *)
        usage && exit 0
        ;;
esac
done

[ -z "${TARGET}" ] && usage && exit 1

source ${THISDIR}/utils

setup_bitbake
${THISDIR}/time_budget bitbake ${TARGET}
_componentsdir="$(get_var_from_bitbake COMPONENTS_DIR)"
## FIXME: don't assume a TMPDIR - get it from bitbake
[ "${TAPGEN}" -ne "0" ] && sudo ${WORKSPACE}/sources/poky/scripts/runqemu-gen-tapdevs `id -u` `id -g` 1 ${_componentsdir}/x86_64/qemu-helper-native/usr/bin
${THISDIR}/time_budget bitbake ${TARGET} -c testimage
# shellcheck disable=SC2086
clean ${CLEAN_SKIP} || true
